import { useState } from 'react';
import DatePicker from 'react-datepicker';
import ArrowForwardIcon from '@material-ui/icons/ArrowForward';
import ArrowBackIcon from '@material-ui/icons/ArrowBack';
import Page from './Page';
import journalStyles from './Journal.module.css';
import 'react-datepicker/dist/react-datepicker.css';
import WidgetDrawer from '../../components/widget-drawer/WidgetDrawer';
import WidgetCalendar from '../../components/calendar/WidgetCalendar';
import WidgetText from '../../components/text/WidgetText';
import WidgetTodo from '../../components/todo/WidgetTodo';
import WidgetHabitTracker from '../../components/habit-tracker/WidgetHabitTracker';
import WidgetYoutubePlayer from '../../components/youtube-player/WidgetYoutubePlayer';
import WidgetWeather from '../../components/weather/WidgetWeather';
import { WidgetTypes } from '../../dnd/WidgetTypes';
import WidgetClock from '../../components/clock/WidgetClock';
import WidgetSteam from '../../components/steam/WidgetSteam';

const axios = require('axios');

const MILLISECONDS_PER_DAY = 1000 * 60 * 60 * 24;
const DAYS_TO_CHANGE_BY = 1;

const Journal = () => {
  const now = new Date();
  const [dateLeftPage, setDateLeftPage] = useState(now.getTime());
  const [dateRightPage, setDateRightPage] = useState(
    now.getTime() + DAYS_TO_CHANGE_BY * MILLISECONDS_PER_DAY
  );

  // widgets active on the left page
  const [widgetsLeft, setWidgetsLeft] = useState([]);
  // widgets active on the right page
  const [widgetsRight, setWidgetsRight] = useState([]);
  // widget will be added on the right page if isRight is true
  const [isRight, setIsRight] = useState(false);

  // Iterate the dates at the top of the journal pages to the previous day
  function handleLeftNav() {
    setDateLeftPage(dateLeftPage - DAYS_TO_CHANGE_BY * MILLISECONDS_PER_DAY);
    setDateRightPage(dateRightPage - DAYS_TO_CHANGE_BY * MILLISECONDS_PER_DAY);
  }

  // Iterate the dates at the top of the journal pages to the next day
  function handleRightNav() {
    setDateLeftPage(dateLeftPage + DAYS_TO_CHANGE_BY * MILLISECONDS_PER_DAY);
    setDateRightPage(dateRightPage + DAYS_TO_CHANGE_BY * MILLISECONDS_PER_DAY);
  }

  // Set the dates at the top of the journal pages to the given date for the left page, and the day after that for the right page
  function handleLeftDatePick(selectedDate) {
    setDateLeftPage(selectedDate.getTime());
    setDateRightPage(selectedDate.getTime() + DAYS_TO_CHANGE_BY * MILLISECONDS_PER_DAY);
  }

  // Set the dates at the top of the journal pages to the given date for the right page, and the day before that for the left page
  function handleRightDatePick(selectedDate) {
    setDateRightPage(selectedDate.getTime());
    setDateLeftPage(selectedDate.getTime() - DAYS_TO_CHANGE_BY * MILLISECONDS_PER_DAY);
  }

  // Formats date from milliseconds to YYYY-MM-DD format.
  function formatDateString(dateMilliseconds) {
    const date = new Date(dateMilliseconds);
    return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().split('T')[0];
  }

  const addNewWidget = (type) => {
    const date = isRight ? formatDateString(dateRightPage) : formatDateString(dateLeftPage);

    const payload = {
      type,
      date,
      position: { row: 0, col: 0 },
    };

    // Requires backend/database to be running to add new widgets
    // as we need to get the widget id generated by the backend.
    axios.post('/api/journal', payload).then(({ data }) => {
      if (isRight) {
        setWidgetsRight([...widgetsRight, data.widget]);
      } else {
        setWidgetsLeft([...widgetsLeft, data.widget]);
      }
    });
  };

  return (
    <div className={journalStyles.JournalContainer}>
      <div className={journalStyles.WidgetDrawerContainer}>
        <WidgetDrawer
          isRight={isRight}
          toggleIsRight={() => {
            setIsRight(!isRight);
          }}
        >
          <WidgetCalendar
            addNewCalendar={() => {
              addNewWidget(WidgetTypes.CALENDAR);
            }}
          />
          <WidgetTodo
            addNewTodo={() => {
              addNewWidget(WidgetTypes.TODO_LIST);
            }}
          />
          <WidgetHabitTracker
            addNewHabitTracker={() => {
              addNewWidget(WidgetTypes.HABIT_TRACKER);
            }}
          />
          <WidgetText
            addNewText={() => {
              addNewWidget(WidgetTypes.TEXT);
            }}
          />
          <WidgetClock
            addNewClock={() => {
              addNewWidget(WidgetTypes.CLOCK);
            }}
          />
          <WidgetYoutubePlayer
            addNewYoutubePlayer={() => {
              addNewWidget(WidgetTypes.YOUTUBE_PLAYER);
            }}
          />
          <WidgetWeather
            addNewWeather={() => {
              addNewWidget(WidgetTypes.WEATHER);
            }}
          />
          <WidgetSteam
            addNewSteam={() => {
              addNewWidget(WidgetTypes.STEAM);
            }}
          />
        </WidgetDrawer>
      </div>
      <div className={journalStyles.Journal}>
        <div className={journalStyles.HalfJournal}>
          <ArrowBackIcon className={journalStyles.ArrowLeft} onClick={handleLeftNav} />
          <DatePicker
            selected={dateLeftPage}
            onChange={(selectedDate) => handleLeftDatePick(selectedDate)}
            dateFormat="MMMM d, yyyy"
            className={journalStyles.DateSelect}
          />
          <Page
            date={formatDateString(dateLeftPage)}
            widgets={widgetsLeft}
            setWidgets={setWidgetsLeft}
          />
        </div>
        <div className={journalStyles.HalfJournal}>
          <DatePicker
            selected={dateRightPage}
            onChange={(selectedDate) => handleRightDatePick(selectedDate)}
            dateFormat="MMMM d, yyyy"
            className={journalStyles.DateSelect}
          />
          <Page
            date={formatDateString(dateRightPage)}
            widgets={widgetsRight}
            setWidgets={setWidgetsRight}
          />
          <ArrowForwardIcon className={journalStyles.ArrowRight} onClick={handleRightNav} />
        </div>
      </div>
    </div>
  );
};

export default Journal;
