name: Backend CI

on:
  pull_request:
    paths:
      - telos-backend/**

defaults:
  run:
    working-directory: telos-backend

jobs:
  backend-ci:
    name: Run Backend Tests and Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test