name: Backend Test

on:
  pull_request:
    paths:
      - telos-backend/**
  push:
    paths:
      - telos-backend/**

defaults:
  run:
    working-directory: telos-backend

jobs:
  test:
    name: Running Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test