name: Frontend Test

on:
  pull_request:
    paths:
      - telos-frontend/**
  push:
    paths:
      - telos-frontend/**

defaults:
  run:
    working-directory: telos-frontend

jobs:
  test:
    name: Running Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run tests
        run: npm test